// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcyadafailnhdzgxdpbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjeWFkYWZhaWxuaGR6Z3hkcGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDEzMDYsImV4cCI6MjA2NTQ3NzMwNn0._7TYHLEHAnahWyPi9jnAdPfmMqDlwWFLmbaIxdx66Qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);